spring.application.name=quickserviceapp
spring.datasource.url=jdbc:mysql://localhost:3306/QuickServiceDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# mail (your own values)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=you@example.com
spring.mail.password=yourpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.successUrl=http://localhost:5173/payment-success?session_id={CHECKOUT_SESSION_ID}
app.frontend.cancelUrl=http://localhost:5173/payment-failed
